---

- hosts: "{{host}}"
  vars:
    - virtenv_path: "{{zstack_root}}/virtualenv/iscsi/"
    - iscsi_root: "{{zstack_root}}/iscsi"
    - file_root: "files/iscsi"
    - pip_url: "{{pypi_url|default('https://pypi.python.org/simple/')}}"
    - proxy: "{{http_proxy|default()}}"
    - sproxy: "{{https_proxy|default()}}"
    - yum_online: "{{yum_online_repo|default('false')}}"

  tasks:
    - include: zstacklib.yaml

    - name: create root directories
      shell: "mkdir -p {{item}}"
      with_items:
        - "{{iscsi_root}}"
        - "{{virtenv_path}}"

    - name: install isci related packages on RedHat based OS from local
      when: ansible_os_family == 'RedHat' and yum_online == 'false'
      shell: "yum clean metadata && yum --disablerepo=* --enablerepo=zstack-local --nogpgcheck install -y wget qemu-img scsi-target-utils && yum clean metadata"

    - name: install isci related packages on RedHat based OS from online
      when: ansible_os_family == 'RedHat' and yum_online != 'false'
      shell: "yum clean metadata && yum --nogpgcheck install -y wget qemu-img scsi-target-utils"

    - name: install isci related packages on Debian based OS
      when: ansible_os_family == 'Debian'
      apt: pkg="{{item}}"
      with_items:
        - iscsitarget
        - iscsitarget-dkms
        - tgt
        - wget
        - qemu-utils

    - name: RHEL7 specific packages from local
      when: ansible_os_family == 'RedHat' and ansible_distribution_version >= '7' and yum_online == 'false'
      shell: "yum clean metadata && yum --disablerepo=* --enablerepo=zstack-local --nogpgcheck install -y iptables-services && yum clean metadata"

    - name: RHEL7 specific packages from online
      when: ansible_os_family == 'RedHat' and ansible_distribution_version >= '7' and yum_online != 'false'
      shell: "yum clean metadata && yum --nogpgcheck install -y iptables-services"

    - name: disable firewalld in RHEL7 and Centos7
      when: ansible_os_family == 'RedHat' and ansible_distribution_version >= '7'
      shell: "(which firewalld && service firewalld stop && chkconfig firewalld off) || true"

    - name: disable selinux on RedHat based OS
      when: ansible_os_family == 'RedHat'
      selinux: state=permissive policy=targeted

    - name: enable tgtd daemon on RedHat
      service: name=tgtd state=started enabled=yes
      when: ansible_os_family == 'RedHat'

    - name: enable tgtd daemon on Debian
      service: name=iscsitarget state=started enabled=yes
      when: ansible_os_family == 'Debian'

    - shell: virtualenv --version | grep "12.1.1"
      register: virtualenv_ret
      ignore_errors: True

    - name: install virtualenv
      pip: name=virtualenv version=12.1.1 extra_args="--ignore-installed --trusted-host {{trusted_host}} -i {{pip_url}}"
      when: virtualenv_ret.rc != 0

    - name: create virtualenv
      shell: "rm -rf {{virtenv_path}} && rm -rf {{iscsi_root}}/{{pkg_zstacklib}} && rm -f {{iscsi_root}}/{{pkg_iscsiagent}} && virtualenv {{virtenv_path}}"

    - name: copy zstacklib
      copy: src="files/zstacklib/{{pkg_zstacklib}}" dest="{{iscsi_root}}/{{pkg_zstacklib}}"
      notify:
        - install zstacklib

    - name: copy iscsi filesystem agent
      copy: src="{{file_root}}/{{pkg_iscsiagent}}" dest="{{iscsi_root}}/{{pkg_iscsiagent}}"
      notify:
        - install iscsiagent

    - name: copy isci service file
      when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'
      copy: src=files/iscsi/zstack-iscsi dest=/etc/init.d/ mode=755

    - meta: flush_handlers

    - name: restart iscsiagent
      service: name=zstack-iscsi state=restarted enabled=yes

  handlers:
    - name: install zstacklib
      environment:
        http_proxy: "{{proxy}}"
        https_proxy: "{{sproxy}}"
      pip: name="{{iscsi_root}}/{{pkg_zstacklib}}" extra_args="--ignore-installed --trusted-host {{trusted_host}} -i {{pip_url}}" virtualenv="{{virtenv_path}}"

    - name: install iscsiagent
      environment:
        http_proxy: "{{proxy}}"
        https_proxy: "{{sproxy}}"
      pip: name="{{iscsi_root}}/{{pkg_iscsiagent}}" extra_args="--ignore-installed --trusted-host {{trusted_host}} -i {{pip_url}}" virtualenv="{{virtenv_path}}"

