---

- hosts: "{{host}}"
  vars:
    - virtenv_path: "{{zstack_root}}/virtualenv/cephb/"
    - cephb_root: "{{zstack_root}}/cephb"
    - file_root: "files/cephb"
    - pip_url: "{{pypi_url|default('https://pypi.python.org/simple/')}}"
    - proxy: "{{http_proxy|default()}}"
    - sproxy: "{{https_proxy|default()}}"
    - yum_online: "{{yum_online_repo|default('false')}}"

  tasks:
    - include: zstacklib.yaml

    - name: create root directories
      shell: "mkdir -p {{item}}"
      with_items:
        - "{{cephb_root}}"
        - "{{virtenv_path}}"

    - name: install dependent packages on RedHat based OS from local
      when: ansible_os_family == 'RedHat' and yum_online == 'false'
      shell: "yum clean metadata && yum --disablerepo=* --enablerepo=zstack-local --nogpgcheck install -y wget qemu-img && yum clean metadata"

    - name: install dependent packages on RedHat based OS from online
      when: ansible_os_family == 'RedHat' and yum_online != 'false'
      shell: "yum clean metadata && yum --nogpgcheck install -y wget qemu-img"

    - name: install dependent packages on Debian based OS
      when: ansible_os_family == 'Debian'
      apt: pkg="{{item}}"
      with_items:
        - wget
        - qemu-utils

    - name: RHEL7 specific packages from local
      when: ansible_os_family == 'RedHat' and ansible_distribution_version >= '7' and yum_online == 'false'
      shell: "yum clean metadata && yum --disablerepo=* --enablerepo=zstack-local --nogpgcheck install -y iptables-services && yum clean metadata"

    - name: RHEL7 specific packages from online
      when: ansible_os_family == 'RedHat' and ansible_distribution_version >= '7' and yum_online != 'false'
      shell: "yum clean metadata && yum --nogpgcheck install -y iptables-services"

    - name: disable firewalld in RHEL7 and Centos7
      when: ansible_os_family == 'RedHat' and ansible_distribution_version >= '7'
      shell: "which firewalld && service firewalld stop && chkconfig firewalld off"

    - name: disable selinux on RedHat based OS
      when: ansible_os_family == 'RedHat'
      selinux: state=permissive policy=targeted

    - shell: virtualenv --version | grep "12.1.1"
      register: virtualenv_ret
      ignore_errors: True

    - name: install virtualenv
      pip: name=virtualenv version=12.1.1 extra_args="--ignore-installed --trusted-host {{trusted_host}} -i {{pip_url}}"
      when: virtualenv_ret.rc != 0

    - name: create virtualenv
      shell: "rm -rf {{virtenv_path}} && rm -rf {{cephb_root}}/{{pkg_zstacklib}} && rm -f {{cephb_root}}/{{pkg_cephbagent}} && virtualenv --system-site-packages {{virtenv_path}}"

    - name: copy zstacklib
      copy: src="files/zstacklib/{{pkg_zstacklib}}" dest="{{cephb_root}}/{{pkg_zstacklib}}"
      notify:
        - install zstacklib

    - name: copy ceph backupstorage agent
      copy: src="{{file_root}}/{{pkg_cephbagent}}" dest="{{cephb_root}}/{{pkg_cephbagent}}"
      notify:
        - install cephbagent

    - name: copy service file
      when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'
      copy: src=files/cephb/zstack-ceph-backupstorage dest=/etc/init.d/ mode=755

    - meta: flush_handlers

    - name: restart cephbagent
      service: name=zstack-ceph-backupstorage state=restarted enabled=yes

  handlers:
    - name: install zstacklib
      environment:
        http_proxy: "{{proxy}}"
        https_proxy: "{{sproxy}}"
      pip: name="{{cephb_root}}/{{pkg_zstacklib}}" extra_args="--ignore-installed --trusted-host {{trusted_host}} -i {{pip_url}}" virtualenv="{{virtenv_path}}"

    - name: install cephbagent
      environment:
        http_proxy: "{{proxy}}"
        https_proxy: "{{sproxy}}"
      pip: name="{{cephb_root}}/{{pkg_cephbagent}}" extra_args="--ignore-installed --trusted-host {{trusted_host}} -i {{pip_url}}" virtualenv="{{virtenv_path}}"

